/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.*;

/**
 *
 * @author coste
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Cuenta c;

    public Principal() {
        initComponents();

        txtNoCuenta.requestFocusInWindow();
        cmdActualizar.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdIngresar.setEnabled(false);
        cmdRetirar.setEnabled(false);
        cmdActualizar.setEnabled(false);
        txtInteres.setEditable(false);
        txtIngresar.setEditable(false);
        txtRetirar.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRetirar = new javax.swing.JTextField();
        txtNoCuenta = new javax.swing.JTextField();
        txtSaldoCuenta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtInteres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIngresar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDatosI = new javax.swing.JTextArea();
        cmdIngresar = new javax.swing.JButton();
        cmdActualizar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdRetirar = new javax.swing.JButton();
        cmdCrear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtIdentificación = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuenta");
        setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Retirar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("No. de cuenta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Saldo de la cuenta");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtRetirar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtRetirar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRetirarKeyTyped(evt);
            }
        });
        jPanel1.add(txtRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 60, -1));

        txtNoCuenta.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNoCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoCuentaKeyTyped(evt);
            }
        });
        jPanel1.add(txtNoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 60, -1));

        txtSaldoCuenta.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtSaldoCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoCuentaKeyTyped(evt);
            }
        });
        jPanel1.add(txtSaldoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 60, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Interés anual");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtInteres.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtInteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 60, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Ingresar a la cuenta");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtIngresar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIngresarKeyTyped(evt);
            }
        });
        jPanel1.add(txtIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 60, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la cuenta", 0, 0, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDatosI.setEditable(false);
        txtDatosI.setColumns(20);
        txtDatosI.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtDatosI.setRows(5);
        jScrollPane1.setViewportView(txtDatosI);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 250, 140));

        cmdIngresar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdIngresar.setText("Ingresar");
        cmdIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 80, -1));

        cmdActualizar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdActualizar.setText("Actualizar");
        cmdActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        cmdMostrar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 80, -1));

        cmdRetirar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdRetirar.setText("Retirar");
        cmdRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRetirarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 80, -1));

        cmdCrear.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 80, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Identificación");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtIdentificación.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtIdentificación.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificaciónKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdentificación, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(397, 413));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoCuentaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtNoCuentaKeyTyped

    private void txtSaldoCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoCuentaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtSaldoCuentaKeyTyped

    private void txtIngresarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtIngresarKeyTyped

    private void txtRetirarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRetirarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtRetirarKeyTyped

    private void txtIdentificaciónKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificaciónKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtIdentificaciónKeyTyped

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        // TODO add your handling code here:
        
        int sw = 1;
        if (txtNoCuenta.getText().trim().isEmpty()) {
            Helper.mensaje(null, "Por favor ingrese los datos correctamente", "Error", 2);
            txtNoCuenta.requestFocusInWindow();
        } else if (txtIdentificación.getText().trim().isEmpty()) {
            Helper.mensaje(null, "Por favor digite los datos correctamente", "Error", 2);
            txtIdentificación.requestFocusInWindow();
        } else if (txtSaldoCuenta.getText().trim().isEmpty()) {
            Helper.mensaje(null, "Por favor digite los datos correctamente", "Error", 2);
            txtSaldoCuenta.requestFocusInWindow();
        } else {
            long n = 0, m = 0, o = 0;
            
            try {
            n = Long.parseLong(txtNoCuenta.getText());
            m = Long.parseLong(txtIdentificación.getText());
            o = Long.parseLong(txtSaldoCuenta.getText());
            } catch(NumberFormatException e) {
                Helper.mensaje(this, "Ingrese un número valido","Error",2);
                sw = 0;
            } 
            
            if (sw == 1){

            c = new Cuenta(n, m, o);

            Helper.mensaje(null, "Cuenta creada satisfactoriamente", "Mensaje", 1);

            cmdActualizar.setEnabled(true);
            txtNoCuenta.setText("");
            txtIdentificación.setText("");
            txtSaldoCuenta.setText("");
            txtNoCuenta.setEditable(false);
            txtIdentificación.setEditable(false);
            txtSaldoCuenta.setEditable(false);
            txtInteres.setEditable(true);
            txtIngresar.setEditable(true);
            txtRetirar.setEditable(true);
            }

        }

    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarActionPerformed
        // TODO add your handling code here:

        if (txtIngresar.getText().trim().isEmpty()) {
            Helper.mensaje(null, "Por favor digite los datos correctamente", "Error", 2);
            txtIngresar.requestFocusInWindow();
        } else {

            double a;
            a = Double.parseDouble(txtIngresar.getText());

            if (a == 0) {
                Helper.mensaje(null, "Al colocar 0 el saldo sera el mismo", "Error", 2);
                txtIngresar.requestFocusInWindow();
            } else {

                c.ingresar(a);
                Helper.mensaje(null, "Su nuevo saldo es de: " + c.getSaldo_actual(), "Mensaje", 1);

                cmdMostrar.setEnabled(true);

            }

        }

    }//GEN-LAST:event_cmdIngresarActionPerformed

    private void cmdRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRetirarActionPerformed
        // TODO add your handling code here:

        if (txtRetirar.getText().trim().isEmpty()) {
            Helper.mensaje(null, "Por favor digite los datos correctamente", "Error", 2);
            txtRetirar.requestFocusInWindow();
        } else {

            double b;
            b = Double.parseDouble(txtRetirar.getText());

            if (b == 0) {
                Helper.mensaje(null, "No puede retirar 0", "Error", 2);
                txtRetirar.requestFocusInWindow();
            } else if (c.getSaldo_actual() < b) {
                Helper.mensaje(null, "Su saldo es insuficiente", "Error", 2);
                txtRetirar.requestFocusInWindow();
                txtRetirar.selectAll();
            } else {

                c.retirar(b);
                Helper.mensaje(null, "Su nuevo saldo es de: " + c.getSaldo_actual(), "Mensaje", 1);

                cmdMostrar.setEnabled(true);

            }

        }

    }//GEN-LAST:event_cmdRetirarActionPerformed

    private void cmdActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActualizarActionPerformed
        // TODO add your handling code here:

        int sw = 1;
        if (txtInteres.getText().trim().isEmpty()) {
            Helper.mensaje(null, "Por favor digite los datos correctamente", "Error", 2);
            txtInteres.requestFocusInWindow();
        } else {

            double d = 0;
            
            try {
            d = Double.parseDouble(txtInteres.getText());
            } catch(NumberFormatException e) {
                Helper.mensaje(this, "Ingrese un número valido","Error",2);
                sw = 0;
                txtInteres.requestFocusInWindow();
                txtInteres.selectAll();
            }
            if (sw == 1) {
                
            
            c.actulizarSaldo(d);

            txtInteres.setEditable(false);
            cmdIngresar.setEnabled(true);
            cmdRetirar.setEnabled(true);
            cmdMostrar.setEnabled(true);

        }
        }
    }//GEN-LAST:event_cmdActualizarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        // TODO add your handling code here:

        String aux;
        aux = c.mostrar();
        txtDatosI.setText(aux);

    }//GEN-LAST:event_cmdMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdActualizar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdIngresar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDatosI;
    private javax.swing.JTextField txtIdentificación;
    private javax.swing.JTextField txtIngresar;
    private javax.swing.JTextField txtInteres;
    private javax.swing.JTextField txtNoCuenta;
    private javax.swing.JTextField txtRetirar;
    private javax.swing.JTextField txtSaldoCuenta;
    // End of variables declaration//GEN-END:variables
}
